apiVersion: v1
kind: Deployment 
metadata:
 name: app-1
spec:
 matchlabel:
  selector:
   name: app1
   purpose: ingress
template:
 metadata:
  name: expense
  labels:
   name: app1
   purpose: ingress
 spec:
  containers:
   - name: nginx
     image: vijaysai/app1:1.0
    
  